language: python
python:
  - "3.5"
# command to run tests
install:
  - pip install codecov coverage
script: nosetests --with-coverage --cover-erase
after_success:
  - coverage
  - bash <(curl -s https://codecov.io/bash)