language: python
python:
  - "3.5"
# command to run tests
script: nosetests --with-coverage
addons:
    code_climate:
        repo_token: a579ac57e49d8392727c84b216289c4754fc55e5a125743810db4333c5b47b42